language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d082586e459ec0fb134
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false