currency:
  name:
    singular: Emerald
    plural: Emeralds
  fractional: true
  denominations:
    388: 1
    133: 9
transactiontax:
  flat: 0.0
  rate: 0.0
usevault:
  container: true
  enderchest: true
