name: Gringotts
author: jastice, squidicuz
version: 0.1
main: net.mcw.gringotts.Gringotts

commands:
  balance:
    aliases: [balance]
    description: Shows your vault balance
    usage: /balance
  money:
  	aliases: [money]
  	description: Money actions
  	usage: /money [add|remove]