name: Gringotts
author: jastice, squidicuz
version: 0.1
depend: [Factions]
main: net.mcw.gringotts.Gringotts

commands:
  balance:
    description: Shows your vault balance
    usage: /balance
  money:
    aliases: [money]
    description: Money actions
    usage: /money [add|remove]