name: Gringotts
authors: [jasticE, squidicuz, eXeC64]
website: https://github.com/MinecraftWars/Gringotts

version: 0.2.1
main: org.gestern.gringotts.Gringotts

depend: []
softdepend: [Factions]

commands:
  balance:
    description: Shows your vault balance
    usage: /balance
    aliases: money
  money:
    aliases: [money]
    description: Money actions
    usage: |
        /money
        /money pay <amount> <player>
    
permissions:
    gringotts.admin:
        description: Use all commands
        default: false